apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: currency-app
  labels:
    app: currency-backend
spec:
  selector:
    app: currency-backend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: NodePort

